[project]
name = "web-scrapper-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "requests>=2.32.3",
    "ruff>=0.8.3",
    "snowflake-sqlalchemy>=1.7.2",
]
